[package]
name = "depressed_mq"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.83"
bincode = "1.3.3"
chrono = "0.4.38"
serde = { version = "1.0.209", features = ["derive"] }
tokio = { version = "1.40.0", features = ["full"] }
